language: python
addons:
  apt:
    packages:
      - pandoc
      - texlive-xetex
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install -r requirements.txt
    - python setup.py install
    - python -c "import pymmd; pymmd.build_mmd()"
script:
    - py.test test/tests.py
