language: python
sudo: required
addons:
  apt:
    packages:
      - pandoc
      - texlive-xetex
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - git clone https://github.com/libgit2/libgit2.git; cd libgit2; mkdir build; cd build; cmake ..; cmake --build . --target install
    - pip install pypandoc
    - pip install -r requirements.txt
    - python setup.py install
    - python -c "import pymmd; pymmd.build_mmd()"
script:
    - py.test test/tests.py
