language: python
addons:
  apt:
    packages:
      - pandoc
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
    - pip install pypandoc pymmd
    - python setup.py install
    - python -c "import pymmd; pymmd.build_mmd()"
script:
    - py.test test/tests.py