environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - cinst miktex pandoc biber.portable
  - refreshenv
  - "%PYTHON%\\python.exe -m pip install wheel pypandoc"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe test/tests.py"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel --universal"

artifacts:
  - path: dist/*
